### ISSUE TITLE
Airlock Middleware causing Carbon date issues.

### ISSUE THREAD

**Issue by mrchrisoliver** [laravel/airlock#65] opened 2020-01-30 10:46 UTC
- Airlock Version: 0.2.0
- Laravel Version: 6.13
- PHP Version: 7.2.24
- Database Driver & Version: sqlsrv
- OS: MacOS 10.14.6
- Docker: Version: 2.2.0.0 Container: microsoft/mssql-server-linux 14.0.3048.4

### Description:
Getting Data Missing error when accessing routes through auth:airlock
Issues are relating to: Carbon/Traits/Creator.php

Usual fix for Models with this issue is to add getDateFormat and fromDateTime functions to the model.

### Steps to reproduce
Installed Airlock 0.20 on Laravel 6.13, using a docker container to run MSSQL.
Set up Airlock Middleware and Authentication Guard as per documentation.
Run the migration files, and set up a User using Tinker.
Accessing an Api route '/enquiry, EnquiryController@index' from an Axios call in VueJS.
EnquiryController@index has dd('test') which doesn't get executed.

If the Api route '/enquiry, EnquiryController@index'  is outside of 'auth:airlock'. I get the correct dd response.

**Comment by driesvints** [comment] 2020-01-30 10:54
Please provide the exact steps to reproduce this.

**Comment by mrchrisoliver** [comment] 2020-01-30 11:28
> Please provide the exact steps to reproduce this.

Updated my initial post. What other information could be useful to help reproduce this?

**Comment by driesvints** [comment] 2020-01-30 11:47
@mrchrisoliver maybe a test repo which we can clone to try things out. Try to commit the base laravel installation and your custom changes separately.

**Comment by mrchrisoliver** [comment] 2020-01-31 21:28
@driesvints  I have added a sample Airlock website to my [Github](https://github.com/mrchrisoliver/airlock)

The error I get is: 
`"message": "Data missing",
    "exception": "InvalidArgumentException",
    "file": "/Users/chris/Documents/Code/airlock/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php",
    "line": 594,`

I believe it has to do with the created_at, updated_at in personal_access_tokens table.
This is the way my dates get formatted: 2020-01-31 21:17:10.837
Laravel/Carbon is expecting: 2020-01-31 21:17:10.837000

I've had many issues with dates similar in the past. I've tried changing settings on MSSQL, Laravel, and PHP ini and have not found a solution yet.

Let me know if I can provide anymore information.

**Comment by driesvints** [comment] 2020-02-03 11:01
I think this maybe is related to a bug in PHP 7.2 which was fixed in PHP 7.3. More info here: https://github.com/laravel/framework/issues/24214

Can you try to see if this gets fixed for you in PHP 7.3?

**Comment by driesvints** [comment] 2020-02-11 14:04
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Closed by driesvints** 2020-02-11 14:04 UTC
Labels: needs more info

**Comment by MdEahiaMondal** [comment] 2020-06-23 16:38
{message: "Auth guard [sunctum] is not defined.", exception: "InvalidArgumentException",…}



why show this message
