### ISSUE TITLE
Consider unique constraint on `user_id` and `name`

### ISSUE THREAD

**Issue by MikeGlennFWC** [laravel/airlock#42] opened 2020-01-14 10:55 UTC
I feel there is a benefit to adding a unique constraint across the columns **user_id** and **name**.

Currently users can create multiple tokens with the same name, meaning differentiating between them at a later date would be impossible as the key is only to be shown **once**.

**Comment by driesvints** [comment] 2020-01-14 13:05
Duplicate of https://github.com/laravel/airlock/issues/25

**Closed by driesvints** 2020-01-14 13:05 UTC

**Comment by MikeGlennFWC** [comment] 2020-01-15 19:01
Can this be reviewed again, #25 has been closed on the first issue.

**Comment by driesvints** [comment] 2020-01-16 13:26
@MikeGlennFWC we won't be enforcing this through the library. You can implement this yourself in your app if you want.
